/// Flutter icons ArtemisIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ArtemisIcons
///      fonts:
///       - asset: fonts/ArtemisIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ArtemisIcons {
  ArtemisIcons._();

  static const _kFontFam = 'ArtemisIcons';
  static const String? _kFontPkg = null;

  static const IconData wifiprinter = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btprinter = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Nav = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Search = IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Clock = IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Refresh = IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Save = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Print = IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Edit = IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Account = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Add = IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Calendar = IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Chart = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left___arrow = IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top_arrow = IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_arrow = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom_arrow = IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right___arrow = IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom = IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Alert = IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData show = IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hidden = IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData server = IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light = IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth = IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
